### ISSUE TITLE
Can this be an extension ?

### ISSUE THREAD

**Issue by ganarajpr** [andrewdavey/immutable-devtools#17]
I think the question suggests everything but - would be great to have this as a chrome extension so that we can enable this as required.

**Comment by langpavel** [comment]
How to detect Immutable objects?
Under the hood this is possible because of special properties on prototype called sentinels:

- `@@__IMMUTABLE_INDEXED__@@`
- `@@__IMMUTABLE_ITERABLE__@@`
- `@@__IMMUTABLE_KEYED__@@`
- `@@__IMMUTABLE_LIST__@@`
- `@@__IMMUTABLE_MAP__@@`
- `@@__IMMUTABLE_ORDERED__@@`
- `@@__IMMUTABLE_SEQ__@@`
- `@@__IMMUTABLE_SET__@@`
- `@@__IMMUTABLE_STACK__@@`

**Comment by mattzeunert** [comment]
I created a Chrome Extension based on Andrew's code.

https://chrome.google.com/webstore/detail/immutablejs-object-format/hgldghadipiblonfkkicmgcbbijnpeog

**Comment by langpavel** [comment]
@mattzeunert Hey you! :+1: Don't be shy, you should link it! [mattzeunert/immutable-object-formatter-extension](https://github.com/mattzeunert/immutable-object-formatter-extension)

There are some issues with Canary (#19) do you test it? I'm curious because it can be Chromium bug.

**Comment by langpavel** [comment]
Closing as this project will not be Chrome extension.

@mattzeunert feel free to edit Readme, add reference to your extension and create PR.

**Comment by Daniel15** [comment]
Thanks for the awesome extension, @mattzeunert! It's working pretty well for me at Facebook :smile:
