### ISSUE TITLE
Failing on Chrome Canary builds

### ISSUE THREAD

**Issue by matthewleon** [andrewdavey/immutable-devtools#19]
On Chrome build 51.0.2689.0 (actually, for versions stretching back for the preceding week or so), attempts to click on a logged Immutable.js object now result in:

`VM562:9 Custom Formatter Failed: ReferenceError: bindRemoteObject is not defined`

I suspect that there's some kind of permanent change to the Custom Formatter API. A few Google searches have revealed precious little information, sadly.

**Comment by awalkerca** [comment]
Version 51.0.2687.0 dev (64-bit)

I'm seeing the same issue on the dev build of stable Chrome.

**Comment by darwin** [comment]
Just FYI. We have the same problem here:
https://github.com/binaryage/cljs-devtools/issues/14

**Comment by langpavel** [comment]
Hi @darwin. Do you think we should delegate this to Chromium? I'm sure that `bindRemoteObject` is not used in this project.

**Comment by darwin** [comment]
The problem seems to be this call:
https://github.com/binaryage/dirac/blob/devtools/front_end/components/CustomPreviewSection.js#L213

It has been there for a long time and that function is not defined anywhere in DevTools code, so I assume it was provided as part of WebKit environment. So I assume someone removed that function or broke it in some way in recent builds. I don't really have time and expertise to go through WebKit/Chromium sources to find what changed at this point.

I believe this will be solved soon when they notice this function is missing. It was probably just renamed or moved elsewhere.

**Comment by mattzeunert** [comment]
It's working for me with the current Chrome Canary.

**Comment by darwin** [comment]
@mattzeunert Please paste here your Chrome version / OS.

It is still broken in Mac Chrome 51.0.2691.0 canary (64-bit). The bug is reproducible when you try to expand a console log generated via custom formatters (by clicking on it's disclosure triangle).

**Comment by mattzeunert** [comment]
@darwin Ah, got it.

**Comment by mattzeunert** [comment]
This is the issue in the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=595206

**Comment by darwin** [comment]
I have just raised the issue upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=599884

**Comment by langpavel** [comment]
Thanks @darwin, I starred the issue.

**Comment by darwin** [comment]
Fixed in 51.0.2702.0 canary (64-bit)

**Comment by langpavel** [comment]
Great! :-)
